// pages/_app.js
import { StoreProvider } from "@/stores";
import RootLayout from "@/app/layout";
import Toast from "@/components/common/Toast";

function MyApp({ Component, pageProps }) {
  console.log("provider runnnig...", StoreProvider);
  const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  return (
    <StoreProvider>
      <RootLayout metadata={metadata}>
        <Toast />
        <Component {...pageProps} />
      </RootLayout>
    </StoreProvider>
  );
}

export default MyApp;
